export const categoryList = [
  {
      id: 1,
      value: 'place',
      label: '🚩 Locations',
  },
  {
      id: 2,
      value: 'dish',
      label: '🍕 Cuisines',
  }
];

export const ratingList = [
  {
      id: 1,
      value: '1',
      label: '1★',
  },
  {
      id: 2,
      value: '2',
      label: '2★',
  },
  {
      id: 3,
      value: '3',
      label: '3★',
  },
  {
      id: 4,
      value: '4',
      label: '4★',
  },
  {
      id: 5,
      value: '5',
      label: '5★',
  },
];


export const locationList = [
  {
      id: 1,
      value: 'Gulshan',
      label: 'Gulshan',
  },
  {
      id: 2,
      value: 'Banani',
      label: 'Banani',
  },
  {
      id: 3,
      value: 'Khilkhet',
      label: 'Khilkhet',
  },
  {
      id: 4,
      value: 'Mirpur',
      label: 'Mirpur',
  },
  {
      id: 5,
      value: 'oldDhaka',
      label: 'Puran Dhaka',
  },
  {
      id: 6,
      value: 'Uttara',
      label: 'Uttara',
  },
  {
      id: 7,
      value: 'Agargoan',
      label: 'Agargoan',
  },
  {
      id: 8,
      value: 'Badda',
      label: 'Badda',
  },
  {
      id: 9,
      value: 'Basurdhara',
      label: 'Basundhara',
  },
  {
      id: 10,
      value: 'Dhanmondi',
      label: 'Dhanmondi',
  },
];

export const foodList = [
  {
      id: 1,
      value: 'Pizza',
      label: 'Pizza',
  },
  {
      id: 2,
      value: 'Burger',
      label: 'Burger',
  },
  {
      id: 3,
      value: 'Biryani',
      label: 'Biryani',
  },
  {
      id: 4,
      value: 'Chicken',
      label: 'Chicken',
  },
  {
      id: 5,
      value: 'Haleem',
      label: 'Haleem',
  },
  {
      id: 6,
      value: 'Steak',
      label: 'Steak',
  },
  {
      id: 7,
      value: 'Chawmein',
      label: 'Chawmein',
  },
  {
      id: 8,
      value: 'Sandwich',
      label: 'Sandwich',
  },
  {
      id: 9,
      value: 'Italian',
      label: 'italian',
  },
  {
      id: 10,
      value: 'Dissert',
      label: 'Dissert',
  },
];
  export const dataList = [
    {
      id: 1,
      title: 'Pizza Hut',
      serviceTime: '45-60min',
      deliveryFee: 3.44,
      category: 'place',
      cuisine: 'pizza',
      foodType: 'Pizza',
      rating: 5,
      price: 1500,
      location:"Gulshan",
      coverSrc: 'https://www.pizzahut.ca/_next/static/static/images/menu/pizzas.ca.fb90341bbc44b9fa9d6bd5436edc38a5.jpg',
    },
    {
      id: 2,
      title: 'Burger King',
      serviceTime: '15-20min',
      deliveryFee: 4.94,
      category: 'place',
      cuisine: 'burger',
      foodType: 'Burger',
      rating: 4,
      price: 1000,
      location:"Banani",
      coverSrc: 'https://www.bigsight.jp/visitor/shop/img/carousel-food-square-01.jpg',
    },
    {
      id: 3,
      title: 'Sultans Dine',
      serviceTime: '30-22min',
      deliveryFee: 4.94,
      category: 'place',
      cuisine: 'biryani',
      foodType: 'Biryani',
      rating: 3,
      price: 2000,
      location:"Khilkhet",
      coverSrc: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcBgVBH0eOqg7gM52Hb_rv519wygFgecGZzg&usqp=CAU',
    },
    {
      id: 4,
      title: 'KFC Mirpur',
      serviceTime: '10-18min',
      deliveryFee: 2.14,
      category: 'place',
      cuisine: 'chicken',
      foodType: 'Fried Chicken',
      rating: 1,
      price: 2500,
      location:"Mirpur",
      coverSrc: 'https://images.deliveryhero.io/image/fd-th/LH/xz8g-hero.jpg?width=512&height=384&quality=45',
    },
    {
      id: 5,
      title: 'Haleem Hub',
      serviceTime: '25-30min',
      deliveryFee: 6.79,
      category: 'place',
      cuisine: 'haleem',
      foodType: 'Haleem',
      rating: 5,
      price: 500,
      location:"oldDhaka",
      coverSrc: 'https://www.thedeliciouscrescent.com/wp-content/uploads/2020/08/Haleem-4.jpg',
    },
    {
      id: 6,
      title: 'TakeOut',
      serviceTime: '5-15min',
      deliveryFee: 2.87,
      category: 'place',
      cuisine: 'steak',
      foodType: 'Steak',
      rating: 5,
      price: 3500,
      location:"Uttara",
      coverSrc: 'https://www.seriouseats.com/thmb/-KA2hwMofR2okTRndfsKtapFG4Q=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__recipes__images__2015__05__Anova-Steak-Guide-Sous-Vide-Photos15-beauty-159b7038c56a4e7685b57f478ca3e4c8.jpg',
      
    },
    {
      id: 7,
      title: 'Chillox',
      serviceTime: '50-65min',
      deliveryFee: 8.5,
      category: 'dish',
      cuisine: 'chawmein',
      foodType: 'Chawmein',
      rating: 2,
      price: 4000,
      location:"Agargoan",
      coverSrc: 'https://www.bigsight.jp/visitor/shop/img/carousel-food-square-01.jpg',
    },
    {
      id: 8,
      title: 'Prezzei',
      serviceTime: '10-15min',
      deliveryFee: 1.8,
      category: 'dish',
      cuisine: 'sandwich',
      foodType: 'Sandwich',
      rating: 1,
      price: 5000,
      location:"Badda",
      coverSrc: 'https://www.bigsight.jp/visitor/shop/img/carousel-food-square-01.jpg',
    },
    {
      id: 9,
      title: 'Spaghetti Jazz',
      serviceTime: '12-18min',
      deliveryFee: 3.33,
      category: 'dish',
      cuisine: 'italian',
      foodType: 'Italian',
      rating: 4,
      price: 1250,
      location:"Basurdhara",
      coverSrc: 'https://www.bigsight.jp/visitor/shop/img/carousel-food-square-01.jpg',
    },
    {
      id: 10,
      title: 'Mithai Dhanmondi',
      serviceTime: '30-38min',
      deliveryFee: 1.9,
      category: 'dish',
      cuisine: 'dissert',
      foodType: 'Dissert',
      rating: 2,
      price: 2300,
      location:"Dhanmondi",
      coverSrc: 'https://www.bigsight.jp/visitor/shop/img/carousel-food-square-01.jpg',
    },
    {
      id: 11,
      title: 'Dominos Pizza',
      serviceTime: '45-60min',
      deliveryFee: 3.44,
      category: 'place',
      cuisine: 'pizza',
      foodType: 'Pizza',
      rating: 5,
      price: 1500,
      location:"Mirpur",
      coverSrc: 'https://www.pizzahut.ca/_next/static/static/images/menu/pizzas.ca.fb90341bbc44b9fa9d6bd5436edc38a5.jpg',
    },
    {
      id: 12,
      title: 'La Pizzaro',
      serviceTime: '45-60min',
      deliveryFee: 3.44,
      category: 'place',
      cuisine: 'pizza',
      foodType: 'Pizza',
      rating: 5,
      price: 1500,
      location:"Dhanmondi",
      coverSrc: 'https://www.pizzahut.ca/_next/static/static/images/menu/pizzas.ca.fb90341bbc44b9fa9d6bd5436edc38a5.jpg',
    }
  ];

